//kalma/frontend/lib/signal-engine/group-labels.ts
//
// Localized display labels for the "affected groups" chips shown on
// signal cards and the place page. The underlying values are stable
// English slugs (e.g. `coffee_growers`) coming from
// signal_type_registry.affected_groups and the activity-profile
// taxonomy. This maps each slug to a human label per locale.
//
// Unknown slugs fall back to the previous behavior — the slug with
// underscores turned into spaces — so a newly added group never breaks
// the chip row; it just shows its raw form until a label is added here.
//
// Self-contained (only the Locale type import) so it can be used from
// server components, client components, and Node scripts alike.

import type { Locale } from './i18n';

type LabelTable = Record<string, string>;

const LABELS: Record<Locale, LabelTable> = {
  en: {
    agriculture: 'agriculture',
    agriculture_general: 'agriculture',
    bean_farmers: 'bean farmers',
    cocoa_growers: 'cocoa growers',
    coffee_farmers: 'coffee farmers',
    coffee_growers: 'coffee growers',
    construction: 'construction',
    cotton_growers: 'cotton growers',
    crop_growers: 'crop growers',
    drainage_operators: 'drainage operators',
    energy_demand: 'energy demand',
    farmers: 'farmers',
    farmers_outdoor: 'outdoor farmers',
    fishing: 'fishing',
    grain_farmers: 'grain farmers',
    grape_growers: 'grape growers',
    horticulture: 'horticulture',
    hydro_operators: 'hydro operators',
    livestock: 'livestock',
    logistics: 'logistics',
    orchards: 'orchards',
    outdoor_events: 'outdoor events',
    outdoor_hospitality: 'outdoor hospitality',
    reservoir_ops: 'reservoir ops',
    rice_farmers: 'rice farmers',
    ski_tourism: 'ski tourism',
    soy_farmers: 'soy farmers',
    street_vendors: 'street vendors',
    sugarcane_growers: 'sugarcane growers',
    tea_growers: 'tea growers',
    tourism: 'tourism',
    vineyards: 'vineyards',
  },
  pt: {
    agriculture: 'agricultura',
    agriculture_general: 'agricultura',
    bean_farmers: 'produtores de feijão',
    cocoa_growers: 'produtores de cacau',
    coffee_farmers: 'cafeicultores',
    coffee_growers: 'cafeicultores',
    construction: 'construção',
    cotton_growers: 'produtores de algodão',
    crop_growers: 'agricultores',
    drainage_operators: 'operadores de drenagem',
    energy_demand: 'demanda de energia',
    farmers: 'agricultores',
    farmers_outdoor: 'agricultores ao ar livre',
    fishing: 'pesca',
    grain_farmers: 'produtores de grãos',
    grape_growers: 'viticultores',
    horticulture: 'horticultura',
    hydro_operators: 'operadores hidrelétricos',
    livestock: 'pecuária',
    logistics: 'logística',
    orchards: 'pomares',
    outdoor_events: 'eventos ao ar livre',
    outdoor_hospitality: 'hospitalidade ao ar livre',
    reservoir_ops: 'operação de reservatórios',
    rice_farmers: 'produtores de arroz',
    ski_tourism: 'turismo de esqui',
    soy_farmers: 'produtores de soja',
    street_vendors: 'vendedores ambulantes',
    sugarcane_growers: 'produtores de cana',
    tea_growers: 'produtores de chá',
    tourism: 'turismo',
    vineyards: 'vinhedos',
  },
  es: {
    agriculture: 'agricultura',
    agriculture_general: 'agricultura',
    bean_farmers: 'productores de frijol',
    cocoa_growers: 'productores de cacao',
    coffee_farmers: 'caficultores',
    coffee_growers: 'caficultores',
    construction: 'construcción',
    cotton_growers: 'productores de algodón',
    crop_growers: 'agricultores',
    drainage_operators: 'operadores de drenaje',
    energy_demand: 'demanda de energía',
    farmers: 'agricultores',
    farmers_outdoor: 'agricultores al aire libre',
    fishing: 'pesca',
    grain_farmers: 'productores de granos',
    grape_growers: 'viticultores',
    horticulture: 'horticultura',
    hydro_operators: 'operadores hidroeléctricos',
    livestock: 'ganadería',
    logistics: 'logística',
    orchards: 'huertos',
    outdoor_events: 'eventos al aire libre',
    outdoor_hospitality: 'hostelería al aire libre',
    reservoir_ops: 'operación de embalses',
    rice_farmers: 'productores de arroz',
    ski_tourism: 'turismo de esquí',
    soy_farmers: 'productores de soja',
    street_vendors: 'vendedores ambulantes',
    sugarcane_growers: 'productores de caña',
    tea_growers: 'productores de té',
    tourism: 'turismo',
    vineyards: 'viñedos',
  },
  fr: {
    agriculture: 'agriculture',
    agriculture_general: 'agriculture',
    bean_farmers: 'producteurs de haricots',
    cocoa_growers: 'producteurs de cacao',
    coffee_farmers: 'caféiculteurs',
    coffee_growers: 'caféiculteurs',
    construction: 'construction',
    cotton_growers: 'producteurs de coton',
    crop_growers: 'cultivateurs',
    drainage_operators: 'opérateurs de drainage',
    energy_demand: 'demande d’énergie',
    farmers: 'agriculteurs',
    farmers_outdoor: 'agriculteurs en plein air',
    fishing: 'pêche',
    grain_farmers: 'producteurs de céréales',
    grape_growers: 'viticulteurs',
    horticulture: 'horticulture',
    hydro_operators: 'exploitants hydroélectriques',
    livestock: 'élevage',
    logistics: 'logistique',
    orchards: 'vergers',
    outdoor_events: 'événements en plein air',
    outdoor_hospitality: 'hôtellerie de plein air',
    reservoir_ops: 'gestion des réservoirs',
    rice_farmers: 'riziculteurs',
    ski_tourism: 'tourisme de ski',
    soy_farmers: 'producteurs de soja',
    street_vendors: 'vendeurs de rue',
    sugarcane_growers: 'producteurs de canne à sucre',
    tea_growers: 'producteurs de thé',
    tourism: 'tourisme',
    vineyards: 'vignobles',
  },
  de: {
    agriculture: 'Landwirtschaft',
    agriculture_general: 'Landwirtschaft',
    bean_farmers: 'Bohnenbauern',
    cocoa_growers: 'Kakaobauern',
    coffee_farmers: 'Kaffeebauern',
    coffee_growers: 'Kaffeebauern',
    construction: 'Bauwesen',
    cotton_growers: 'Baumwollbauern',
    crop_growers: 'Ackerbauern',
    drainage_operators: 'Entwässerungsbetriebe',
    energy_demand: 'Energiebedarf',
    farmers: 'Landwirte',
    farmers_outdoor: 'Freiland-Landwirte',
    fishing: 'Fischerei',
    grain_farmers: 'Getreidebauern',
    grape_growers: 'Winzer',
    horticulture: 'Gartenbau',
    hydro_operators: 'Wasserkraftbetreiber',
    livestock: 'Viehhaltung',
    logistics: 'Logistik',
    orchards: 'Obstplantagen',
    outdoor_events: 'Outdoor-Veranstaltungen',
    outdoor_hospitality: 'Outdoor-Gastgewerbe',
    reservoir_ops: 'Stauseebetrieb',
    rice_farmers: 'Reisbauern',
    ski_tourism: 'Ski-Tourismus',
    soy_farmers: 'Sojabauern',
    street_vendors: 'Straßenhändler',
    sugarcane_growers: 'Zuckerrohrbauern',
    tea_growers: 'Teebauern',
    tourism: 'Tourismus',
    vineyards: 'Weinberge',
  },
  zh: {
    agriculture: '农业',
    agriculture_general: '农业',
    bean_farmers: '豆农',
    cocoa_growers: '可可种植者',
    coffee_farmers: '咖啡农',
    coffee_growers: '咖啡种植者',
    construction: '建筑业',
    cotton_growers: '棉农',
    crop_growers: '种植户',
    drainage_operators: '排水运营方',
    energy_demand: '能源需求',
    farmers: '农户',
    farmers_outdoor: '露天农户',
    fishing: '渔业',
    grain_farmers: '粮农',
    grape_growers: '葡萄种植者',
    horticulture: '园艺',
    hydro_operators: '水电运营方',
    livestock: '畜牧业',
    logistics: '物流',
    orchards: '果园',
    outdoor_events: '户外活动',
    outdoor_hospitality: '户外接待业',
    reservoir_ops: '水库运营',
    rice_farmers: '稻农',
    ski_tourism: '滑雪旅游',
    soy_farmers: '大豆种植者',
    street_vendors: '街头摊贩',
    sugarcane_growers: '甘蔗种植者',
    tea_growers: '茶农',
    tourism: '旅游业',
    vineyards: '葡萄园',
  },
};

/**
 * Localized chip label for an affected-group slug. Unknown slugs fall
 * back to the slug with underscores replaced by spaces (previous
 * behavior), so an unseen group renders gracefully in any locale.
 */
export function groupLabel(locale: Locale, slug: string): string {
  const table = LABELS[locale] ?? LABELS.en;
  return table[slug] ?? LABELS.en[slug] ?? slug.replace(/_/g, ' ');
}
